### ISSUE TITLE
[코멘트 요청] 타임스탬프 사용할 경우 문제점

### ISSUE THREAD

**Issue by Hong-Seungmin** [Hong-Seungmin/HangHae99_Chapter3#2]
안녕하세요 매니저님,
코멘트 요청 드립니다.

게시글을 보관하는 Board클래스에 조회수를 기록하고자 Long views 추가해보았습니다.
Board클래스는 Timestamped를 상속받아 변경시간이 자동으로 기록되는 상황입니다.

여기서 매번 조회가 일어날때마다 views가 증가하도록하였는데, (변경발생)
게시글 자체 변경시간인 modifiedAt까지 갱신되어버리는 상황이 발생하였습니다.

1. AuditingEntityListener에서 특정 필드만 제외할 방법은 없을까요?
2. 아니면 조회수 같은 부가데이터는 따로 별도의 테이블에서 관리하는것이 좋을까요? 

ps. 이슈등록 처음해보는데, 이렇게 하는게 맞을까요? ㅎㅎ;;

---

### Timestamped.java  ( 자식객체의 생성/변경 시간 기록 )
```java
@Getter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public class Timestamped {

    @CreatedDate
    private LocalDateTime createdAt;

    @LastModifiedDate
    private LocalDateTime modifiedAt;
}
```

### Board.java (게시글 클래스 )
```java
@Getter
@NoArgsConstructor
@Entity
public class Board extends Timestamped {

    //.....

    @Column(nullable = false)
    private Long views;

    public Board(BoardDto boardDto) {
        //.....
        this.views = 1L;
    }

    //.......

    public void increaseView(){
        this.views += 1;
    }
}
```

**Comment by zzangoobrother** [comment]
안녕하세요. 최선강입니다.

한 주 동안 고생하셨습니다.
createdAt -> 데이터 등록시간, modifiedAt -> 데이터 수정시간으로 조회수가 올라간거는 수정되었다는 거고 당연히 modifiedAt의 시간은 변경된 시간으로 바뀔 겁니다. 실무에서도 데이터마다 등록시간과 수정시간이 같이 있습니다. 데이터 유지보수하는데 있어 필수 사항입니다.
테이블을 따로 둔다고 하면 많은 테이블에 등록시간과 수정시간이 있을 텐데 모두 따로 관리하면 관리하는 비용이 더 많이 발생합니다.

**Comment by Hong-Seungmin** [comment]
네 답변감사합니다. 테이블을 따로 둔다는것이.. 조회수를 기록하는 View에 대한 테이블을 만들어보는것이 어떨까하다는 의견이였습니다 ㅎㅎ

기존에는 board테이블에 views라는 컬럼을 넣었다만, 이렇게하니 view의 증가가 modified로 인식하기에..

우선.. 어느정도 JPA 구조를 익히고나니 따로두는것이 맞다는것으로 결론을 짓긴하였습니다!
